### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by dylanaraps** [kissx/kiss#1]
- [x] Detach `kiss` from the repository location.
- [x] Proper dependency resolver.
- [x] Add `$PATH` like variable for repositories.
- [x] Write documentation for setup.
